lib/tasks_web/router.ex
defmodule TasksWeb.Router do
  use TasksWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug TasksWeb.Plugs.FetchSession
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", TasksWeb do
    pipe_through :browser

    get "/", PageController, :index
    get "/tasks", PageController, :index
    get "/users", PageController, :index
  end

  scope "/api", TasksWeb do
     pipe_through :api

     resources "/users", UserController, except: [:new, :edit]
     resources "/tasks", TaskController, except: [:new, :edit]
     post "/auth", SessionController, :create
   end
end

lib/tasks/users.ex
defmodule Tasks.Users do
  @moduledoc """
  The Users context.
  """

  import Ecto.Query, warn: false
  alias Tasks.Repo

  alias Tasks.Users.User

  @doc """
  Returns the list of users.

  ## Examples

      iex> list_users()
      [%User{}, ...]

  """
  def list_users do
    Repo.all(from u in User)
  end

  @doc """
  Gets a single user.

  Raises `Ecto.NoResultsError` if the User does not exist.

  ## Examples

      iex> get_user!(123)
      %User{}

      iex> get_user!(456)
      ** (Ecto.NoResultsError)

  """
  def get_user!(id) do
    Repo.one!(from u in User,
      where: u.id == ^id)
  end

  # taken from Nat Tuck's users impl: https://khoury.neu.edu/~ntuck/courses/2019/01/cs4550/notes/11-add-users/notes.html
  def get_user(id), do: Repo.get(User, id)

  def get_user_by_email(email) do
    Repo.one(from u in User,
              where: u.email == ^email)
  end

  @doc """
  Creates a user.

  ## Examples

      iex> create_user(%{field: value})
      {:ok, %User{}}

      iex> create_user(%{field: bad_value})
      {:error, %Ecto.Changeset{}}

  """
  def create_user(attrs \\ %{}) do
    password_hash = Argon2.hash_pwd_salt(attrs["password"])
    attrs = attrs
    |> Map.put("password_hash", password_hash)

    %User{}
    |> User.changeset(attrs)
    |> Repo.insert()
  end

  @doc """
  Updates a user.

  ## Examples

      iex> update_user(user, %{field: new_value})
      {:ok, %User{}}

      iex> update_user(user, %{field: bad_value})
      {:error, %Ecto.Changeset{}}

  """
  def update_user(%User{} = user, attrs) do
    user
    |> User.changeset(attrs)
    |> Repo.update()
  end

  @doc """
  Deletes a User.

  ## Examples

      iex> delete_user(user)
      {:ok, %User{}}

      iex> delete_user(user)
      {:error, %Ecto.Changeset{}}

  """
  def delete_user(%User{} = user) do
    Repo.delete(user)
  end

  @doc """
  Returns an `%Ecto.Changeset{}` for tracking user changes.

  ## Examples

      iex> change_user(user)
      %Ecto.Changeset{source: %User{}}

  """
  def change_user(%User{} = user) do
    User.changeset(user, %{})
  end
end

lib/tasks/users/user.ex
defmodule Tasks.Users.User do
  use Ecto.Schema
  import Ecto.Changeset


  schema "users" do
    field :email, :string
    field :password_hash, :string
    has_many :tasks, Tasks.Tasks.Task, foreign_key: :assignee_id, on_delete: :nilify_all

    timestamps()
  end

  @doc false
  def changeset(user, attrs) do
    user
    |> cast(attrs, [:email, :password_hash])
    |> validate_required([:email])
  end
end

lib/tasks_web/controllers/user_controller.ex
defmodule TasksWeb.UserController do
  use TasksWeb, :controller

  alias Tasks.Users
  alias Tasks.Users.User

  def index(conn, _params) do
    users = Users.list_users()
    render(conn, "index.json", users: users)
  end

  def create(conn, %{"user" => user_params}) do
    with {:ok, user} <- Users.create_user(user_params) do
      conn
      |> render("show.json", user: user)
    end
  end

  def show(conn, %{"id" => id}) do
    user = Users.get_user!(id)
    render(conn, "show.json", user: user)
  end

  def update(conn, %{"id" => id, "user" => user_params}) do
    user = Users.get_user!(id)

    with {:ok, user} <- Users.update_user(user, user_params) do
      conn
      |> put_flash(:info, "User updated successfully.")
      |> render("show.json", user: user)
    end
  end

  def delete(conn, %{"id" => id}) do
    user = Users.get_user!(id)
    with {:ok, _user} <- Users.delete_user(user) do
      conn
      |> put_flash(:info, "User deleted successfully.")
    end
  end
end

lib/tasks_web/views/user_view.ex
defmodule TasksWeb.UserView do
  use TasksWeb, :view

  def render("index.json", %{users: users}) do
    %{data: render_many(users, TasksWeb.UserView, "user.json")}
  end

  def render("show.json", %{user: user}) do
    %{data: render_one(user, TasksWeb.UserView, "user.json")}
  end

  def render("user.json", %{user: user}) do
    %{id: user.id,
      email: user.email}
  end
end

lib/tasks_web/templates/user/edit.html.eex
<h1>Edit User</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.user_path(@conn, :update, @user)) %>

<span><%= link "Back", to: Routes.user_path(@conn, :index) %></span>

lib/tasks_web/templates/user/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <%= label f, :email %>
  <%= text_input f, :email %>
  <%= error_tag f, :email %>

  <div>
    <%= submit "Save" %>
  </div>
<% end %>

lib/tasks_web/templates/user/index.html.eex
<h1>Listing Users</h1>

<%= render TasksWeb.UserView, "user_list.html", users: @users, conn: @conn %>

<span><%= link "New User", to: Routes.user_path(@conn, :new) %></span>

lib/tasks_web/templates/user/new.html.eex
<h1>New User</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.user_path(@conn, :create)) %>

<span><%= link "Back", to: Routes.user_path(@conn, :index) %></span>

lib/tasks_web/templates/user/show.html.eex
<h1>User:</h1>

<ul>

  <li>
    <strong>Email:</strong>
    <%= @user.email %>
  </li>
  <li>
    <%= link "User's Tasks", to: "/tasks/personal?user_id=#{@user.id}" %>
  </li>
  <li>
    <%= link "Edit", to: Routes.user_path(@conn, :edit, @user) %>
  </li>
  <li>
    <span><%= link "Back", to: Routes.user_path(@conn, :index) %></span>
  </li>
</ul>

<%= if @user.is_manager do
  render TasksWeb.UserView, "manager_section.html", user: @user, conn: @conn
end %>

lib/tasks_web/templates/user/user_list.html.eex
<table>
  <thead>
    <tr>
      <th>Email</th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for user <- @users do %>
    <tr>
      <td><%= user.email %></td>

      <td>
        <%= link "Show", to: Routes.user_path(@conn, :show, user) %>
      </td>
      <td>
        <%= link "Edit", to: Routes.user_path(@conn, :edit, user) %>
      </td>
      <td>
        <%= link "Delete", to: Routes.user_path(@conn, :delete, user), method: :delete, data: [confirm: "Are you sure?"] %>
      </td>
      <td>
        <%= link "Tasks", to: "/tasks/personal?user_id=#{user.id}" %>
      </td>
    </tr>
<% end %>
  </tbody>
</table>